name: 'Echo ENVs'
run: |
  echo 'Environment ENV_FOO =  ${{ secrets.ENV_FOO }}'  
  echo $(git branch --show-current)
  echo $(git branch --show-current | sed "s#.*/##g")
  echo 'repository ${{ github.repository }}'
  echo 'repository_owner ${{ github.repository_owner }}'
