name: Environment variables and secrets

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'

env:
  APP_NAME: frontend-application
  
jobs:
  echo_production:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Echo build environment vars
        uses: ./.github/actions/echo
        # - name: Check out this repo
        #   uses: actions/checkout@v3
      
#   echo_acceptance:
#     runs-on: ubuntu-latest
#     environment: acceptance
#     steps:
#     - name: Check out this repo
#       uses: actions/checkout@v3
#       with:
#         fetch-depth: 0

#     - name: Echo build environment vars
#       uses: ./.github/actions/echo

#   echo_test:
#     runs-on: ubuntu-latest
#     environment: test
#     steps:
#     - name: Check out this repo
#       uses: actions/checkout@v3
#       with:
#         fetch-depth: 0

#     - name: Echo build environment vars
#       uses: .github/actions/echo
