name: Environment variables and secrets

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-signature-portal.yml'

env:
  APP_NAME: frontend-application
  
jobs:
  EchoEnvironment:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Echo build environment vars
      run: |
        echo $(git branch --show-current | sed "s#.*/##g")
        echo $PULL_REQUEST
        echo $GITHUB_ENV
        echo ${{ env }}

# LAB_IMAGE_NAME1="$LAB_AWS_ECR_REPO/signing-portal:$RELEASE_ID"
# if [ "$PULL_REQUEST" = "000" ]; then
#   branch_name=$(git branch --show-current | sed "s#.*/##g")
#   LAB_IMAGE_NAME2="$LAB_AWS_ECR_REPO/signing-portal:$branch_name"
# else
#   LAB_IMAGE_NAME2="$LAB_AWS_ECR_REPO/signing-portal:pr-$PULL_REQUEST"
# fi
# docker tag $IMAGE_NAME $LAB_IMAGE_NAME1
# docker tag $IMAGE_NAME $LAB_IMAGE_NAME2
# echo "LAB_IMAGE_NAME1=$LAB_IMAGE_NAME1" >> $GITHUB_ENV
# echo "LAB_IMAGE_NAME2=$LAB_IMAGE_NAME2" >> $GITHUB_ENV