name: Environment variables and secrets

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'

env:
  APP_NAME: frontend-application
  
jobs:
  echo_production:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Check out this repo
      uses: ./.github/actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Echo build environment vars
      uses: ./.github/actions/echo
      
  echo_acceptance:
    runs-on: ubuntu-latest
    environment: acceptance
    steps:
    - name: Check out this repo
      uses: ./.github/actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Echo build environment vars
      uses: haikodejong-cleverbase/prototype-environment-secrets/.github/actions/echo

  echo_test:
    runs-on: ubuntu-latest
    environment: test
    steps:
    - name: Check out this repo
      uses: haikodejong-cleverbase/prototype-environment-secrets/.github/actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Echo build environment vars
      uses: haikodejong-cleverbase/prototype-environment-secrets/.github/actions/echo
